"""Compatibility facade for TFR-owned GEPA optimization modules."""

from app.services.optimization import (
    DEMO_FORM_ID,
    DEMO_FORM_VERSION,
    AuditPromptProgram,
    CancelFileStopper,
    OptimizationArtifactWriter,
    OptimizationDataInstance,
    OptimizationRepository,
    OptimizationRolloutOutput,
    OptimizationRunCallback,
    OptimizationRunService,
    OptimizationTrajectory,
    ProposalOutput,
    ReflectionInput,
    TFRGepaAdapter,
    UpdatedComponent,
    apply_split_helper,
    build_reflection_input,
    ensure_demo_fixture,
    propose_new_texts,
    run_optimization_job,
    serialize_messages,
)

_serialize_messages = serialize_messages

__all__ = [
    "DEMO_FORM_ID",
    "DEMO_FORM_VERSION",
    "AuditPromptProgram",
    "CancelFileStopper",
    "OptimizationArtifactWriter",
    "OptimizationDataInstance",
    "OptimizationRepository",
    "OptimizationRolloutOutput",
    "OptimizationRunCallback",
    "OptimizationRunService",
    "OptimizationTrajectory",
    "ProposalOutput",
    "ReflectionInput",
    "TFRGepaAdapter",
    "UpdatedComponent",
    "_serialize_messages",
    "apply_split_helper",
    "build_reflection_input",
    "ensure_demo_fixture",
    "propose_new_texts",
    "run_optimization_job",
    "serialize_messages",
]
