"""initial schema

Revision ID: 9800769b7b4a
Revises:
Create Date: 2026-05-12 21:02:35.882208

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# ruff: noqa: E501

revision: str = "9800769b7b4a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_batch_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("form_id", sa.String(length=128), nullable=False),
        sa.Column("form_version", sa.String(length=64), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("synthetic_count", sa.Integer(), nullable=False),
        sa.Column("input_mode", sa.String(length=24), nullable=False),
        sa.Column(
            "excel_column_map",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "items_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_batch_templates")),
    )
    with op.batch_alter_table("audit_batch_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_batch_templates_form_id"), ["form_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_batch_templates_form_version"), ["form_version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_batch_templates_name"), ["name"], unique=False)

    op.create_table(
        "eval_datasets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("form_id", sa.String(length=128), nullable=False),
        sa.Column("form_version", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column(
            "source_metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_datasets")),
    )
    with op.batch_alter_table("eval_datasets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eval_datasets_dataset_hash"), ["dataset_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_eval_datasets_form_id"), ["form_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_eval_datasets_form_version"), ["form_version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_eval_datasets_name"), ["name"], unique=False)

    op.create_table(
        "audit_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column(
            "input_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["audit_batch_templates.id"],
            name=op.f("fk_audit_batches_template_id_audit_batch_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_batches")),
    )
    with op.batch_alter_table("audit_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_batches_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_batches_template_id"), ["template_id"], unique=False
        )

    op.create_table(
        "eval_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("claim_number", sa.String(length=128), nullable=False),
        sa.Column("effective_date", sa.String(length=64), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column(
            "input_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["eval_datasets.id"],
            name=op.f("fk_eval_cases_dataset_id_eval_datasets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_cases")),
    )
    with op.batch_alter_table("eval_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eval_cases_claim_number"), ["claim_number"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_eval_cases_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "eval_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("lineage_id", sa.String(length=36), nullable=True),
        sa.Column("source_run_id", sa.String(length=36), nullable=True),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("reference_policy", sa.String(length=32), nullable=False),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column("retry_limit", sa.Integer(), nullable=False),
        sa.Column("enable_mlflow", sa.Boolean(), nullable=False),
        sa.Column("mlflow_run_id", sa.String(length=128), nullable=True),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column(
            "input_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["eval_datasets.id"], name=op.f("fk_eval_runs_dataset_id_eval_datasets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_runs_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_runs_lineage_id"), ["lineage_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_runs_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_eval_runs_source_run_id"), ["source_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_eval_runs_status"), ["status"], unique=False)

    op.create_table(
        "audit_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("form_id", sa.String(length=128), nullable=False),
        sa.Column("form_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "input_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("original_result_version_id", sa.String(length=36), nullable=True),
        sa.Column("current_user_result_version_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["audit_batches.id"],
            name=op.f("fk_audit_reviews_batch_id_audit_batches"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_reviews")),
    )
    with op.batch_alter_table("audit_reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_reviews_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_reviews_form_id"), ["form_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_reviews_form_version"), ["form_version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_reviews_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_reviews_status"), ["status"], unique=False)

    op.create_table(
        "eval_ground_truths",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("reference_kind", sa.String(length=16), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reviewer", sa.String(length=120), nullable=True),
        sa.Column(
            "source_metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["eval_cases.id"], name=op.f("fk_eval_ground_truths_case_id_eval_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_ground_truths")),
    )
    with op.batch_alter_table("eval_ground_truths", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eval_ground_truths_case_id"), ["case_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_eval_ground_truths_reference_kind"), ["reference_kind"], unique=False
        )

    op.create_table(
        "audit_result_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["audit_reviews.id"],
            name=op.f("fk_audit_result_versions_review_id_audit_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_result_versions")),
    )
    with op.batch_alter_table("audit_result_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_result_versions_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_result_versions_payload_hash"), ["payload_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_result_versions_review_id"), ["review_id"], unique=False
        )

    op.create_table(
        "eval_run_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("generated_review_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["eval_cases.id"], name=op.f("fk_eval_run_items_case_id_eval_cases")
        ),
        sa.ForeignKeyConstraint(
            ["generated_review_id"],
            ["audit_reviews.id"],
            name=op.f("fk_eval_run_items_generated_review_id_audit_reviews"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["eval_runs.id"], name=op.f("fk_eval_run_items_run_id_eval_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_run_items")),
    )
    with op.batch_alter_table("eval_run_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_run_items_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_eval_run_items_generated_review_id"),
            ["generated_review_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_eval_run_items_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_run_items_status"), ["status"], unique=False)

    op.create_table(
        "review_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("evaluator", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["audit_reviews.id"],
            name=op.f("fk_review_evaluations_review_id_audit_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_evaluations")),
    )
    with op.batch_alter_table("review_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_evaluations_review_id"), ["review_id"], unique=False
        )

    op.create_table(
        "review_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["audit_reviews.id"],
            name=op.f("fk_review_feedback_review_id_audit_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_feedback")),
    )
    with op.batch_alter_table("review_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_feedback_review_id"), ["review_id"], unique=False
        )

    op.create_table(
        "audit_question_answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("result_version_id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("question_id", sa.String(length=64), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("answer", sa.String(length=8), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_version_id"],
            ["audit_result_versions.id"],
            name=op.f("fk_audit_question_answers_result_version_id_audit_result_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["audit_reviews.id"],
            name=op.f("fk_audit_question_answers_review_id_audit_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_question_answers")),
    )
    with op.batch_alter_table("audit_question_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_question_answers_answer"), ["answer"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_question_answers_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_question_answers_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_question_answers_result_version_id"),
            ["result_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_question_answers_review_id"), ["review_id"], unique=False
        )

    op.create_table(
        "audit_subquestion_answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("result_version_id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("question_id", sa.String(length=64), nullable=False),
        sa.Column("subquestion_id", sa.String(length=64), nullable=False),
        sa.Column("subquestion_text", sa.Text(), nullable=False),
        sa.Column("answer", sa.Boolean(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("citations", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_version_id"],
            ["audit_result_versions.id"],
            name=op.f("fk_audit_subquestion_answers_result_version_id_audit_result_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["audit_reviews.id"],
            name=op.f("fk_audit_subquestion_answers_review_id_audit_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_subquestion_answers")),
    )
    with op.batch_alter_table("audit_subquestion_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_subquestion_answers_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_subquestion_answers_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_subquestion_answers_result_version_id"),
            ["result_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_subquestion_answers_review_id"), ["review_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_subquestion_answers_subquestion_id"),
            ["subquestion_id"],
            unique=False,
        )

    op.create_table(
        "eval_comparisons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("run_item_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("ground_truth_id", sa.String(length=36), nullable=False),
        sa.Column("reference_kind", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "metrics_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["eval_cases.id"], name=op.f("fk_eval_comparisons_case_id_eval_cases")
        ),
        sa.ForeignKeyConstraint(
            ["ground_truth_id"],
            ["eval_ground_truths.id"],
            name=op.f("fk_eval_comparisons_ground_truth_id_eval_ground_truths"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["eval_runs.id"], name=op.f("fk_eval_comparisons_run_id_eval_runs")
        ),
        sa.ForeignKeyConstraint(
            ["run_item_id"],
            ["eval_run_items.id"],
            name=op.f("fk_eval_comparisons_run_item_id_eval_run_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_comparisons")),
    )
    with op.batch_alter_table("eval_comparisons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_comparisons_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_eval_comparisons_ground_truth_id"), ["ground_truth_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_eval_comparisons_reference_kind"), ["reference_kind"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_eval_comparisons_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_eval_comparisons_run_item_id"), ["run_item_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eval_comparisons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_comparisons_run_item_id"))
        batch_op.drop_index(batch_op.f("ix_eval_comparisons_run_id"))
        batch_op.drop_index(batch_op.f("ix_eval_comparisons_reference_kind"))
        batch_op.drop_index(batch_op.f("ix_eval_comparisons_ground_truth_id"))
        batch_op.drop_index(batch_op.f("ix_eval_comparisons_case_id"))

    op.drop_table("eval_comparisons")
    with op.batch_alter_table("audit_subquestion_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_subquestion_answers_subquestion_id"))
        batch_op.drop_index(batch_op.f("ix_audit_subquestion_answers_review_id"))
        batch_op.drop_index(batch_op.f("ix_audit_subquestion_answers_result_version_id"))
        batch_op.drop_index(batch_op.f("ix_audit_subquestion_answers_question_id"))
        batch_op.drop_index(batch_op.f("ix_audit_subquestion_answers_kind"))

    op.drop_table("audit_subquestion_answers")
    with op.batch_alter_table("audit_question_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_question_answers_review_id"))
        batch_op.drop_index(batch_op.f("ix_audit_question_answers_result_version_id"))
        batch_op.drop_index(batch_op.f("ix_audit_question_answers_question_id"))
        batch_op.drop_index(batch_op.f("ix_audit_question_answers_kind"))
        batch_op.drop_index(batch_op.f("ix_audit_question_answers_answer"))

    op.drop_table("audit_question_answers")
    with op.batch_alter_table("review_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_feedback_review_id"))

    op.drop_table("review_feedback")
    with op.batch_alter_table("review_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_evaluations_review_id"))

    op.drop_table("review_evaluations")
    with op.batch_alter_table("eval_run_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_run_items_status"))
        batch_op.drop_index(batch_op.f("ix_eval_run_items_run_id"))
        batch_op.drop_index(batch_op.f("ix_eval_run_items_generated_review_id"))
        batch_op.drop_index(batch_op.f("ix_eval_run_items_case_id"))

    op.drop_table("eval_run_items")
    with op.batch_alter_table("audit_result_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_result_versions_review_id"))
        batch_op.drop_index(batch_op.f("ix_audit_result_versions_payload_hash"))
        batch_op.drop_index(batch_op.f("ix_audit_result_versions_kind"))

    op.drop_table("audit_result_versions")
    with op.batch_alter_table("eval_ground_truths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_ground_truths_reference_kind"))
        batch_op.drop_index(batch_op.f("ix_eval_ground_truths_case_id"))

    op.drop_table("eval_ground_truths")
    with op.batch_alter_table("audit_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_reviews_status"))
        batch_op.drop_index(batch_op.f("ix_audit_reviews_source"))
        batch_op.drop_index(batch_op.f("ix_audit_reviews_form_version"))
        batch_op.drop_index(batch_op.f("ix_audit_reviews_form_id"))
        batch_op.drop_index(batch_op.f("ix_audit_reviews_batch_id"))

    op.drop_table("audit_reviews")
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_runs_status"))
        batch_op.drop_index(batch_op.f("ix_eval_runs_source_run_id"))
        batch_op.drop_index(batch_op.f("ix_eval_runs_name"))
        batch_op.drop_index(batch_op.f("ix_eval_runs_lineage_id"))
        batch_op.drop_index(batch_op.f("ix_eval_runs_dataset_id"))

    op.drop_table("eval_runs")
    with op.batch_alter_table("eval_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_cases_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_eval_cases_claim_number"))

    op.drop_table("eval_cases")
    with op.batch_alter_table("audit_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_batches_template_id"))
        batch_op.drop_index(batch_op.f("ix_audit_batches_status"))

    op.drop_table("audit_batches")
    with op.batch_alter_table("eval_datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_datasets_name"))
        batch_op.drop_index(batch_op.f("ix_eval_datasets_form_version"))
        batch_op.drop_index(batch_op.f("ix_eval_datasets_form_id"))
        batch_op.drop_index(batch_op.f("ix_eval_datasets_dataset_hash"))

    op.drop_table("eval_datasets")
    with op.batch_alter_table("audit_batch_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_batch_templates_name"))
        batch_op.drop_index(batch_op.f("ix_audit_batch_templates_form_version"))
        batch_op.drop_index(batch_op.f("ix_audit_batch_templates_form_id"))

    op.drop_table("audit_batch_templates")
    # ### end Alembic commands ###
